mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.http.response import HttpResponseRedirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('outdooradventures/', include('outdooradventures.urls')),
]

outdooradventures/urls.py
from django.urls import path
import datetime
from django.utils import timezone

from . import views

app_name = 'outdooradventures'

urlpatterns = [
    path('', views.index, name='index'),
    path('activities/', views.activities, name='activities'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('createpost/', views.createpost, name='createpost'),

]


"""
path('destinations', views.destinations, name='destinations'),
path('userprofile/<int:user_id>/', views.userprofile, name='userprofile'),
path('clubprofile/<int:club_id>/', views.clubprofile, name='clubprofile'),
path('userdashboard/<int:user_id>/', views.userdashboard, name='userdashboard'),
path('clubdashboard/<int:club_id>/', views.clubdashboard, name='clubdashboard'),

"""

outdooradventures/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField


class Club(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=200)
    phone_number = PhoneNumberField()
    website= models.URLField()
    description = models.TextField()

    def __str__(self):
     return "%s" % (self.fullname)

class Adress(models.Model):
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    code = models.CharField(max_length=10)

    def __str__(self):
     return "%s adress" % (self.club)

class Activity(models.Model):
    name = models.CharField(max_length=200)
    clubs = models.ManyToManyField(Club)

    def __str__(self):
     return "%s" % (self.name)

class Post(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    activity= models.ForeignKey(Activity, on_delete=models.CASCADE)
    region= models.CharField(max_length=100)
    no_participants= models.PositiveSmallIntegerField()
    date=models.DateField()
    comments=models.TextField()


class Offer(models.Model):
    post= models.ForeignKey(Post, on_delete=models.CASCADE)
    club= models.ForeignKey(Club, on_delete=models.CASCADE)
    price =models.DecimalField(max_digits=8, decimal_places=2)
    comments=models.TextField()

    STATUS_CHOICES = (
    (1, 'Not answered'),
    (2, 'Accepted'),
    (3, 'Declined'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)

outdooradventures/forms.py
from django import forms

class CreatePostForm(forms.Form):
    activity = forms.CharField(label='activity', max_length=100)
    destination = forms.CharField(label='destination', max_length=100)
    noparticipants = forms.IntegerField(label='participants', max_value=80)
    date = forms.DateField()
    comments = forms.CharField(widget=forms.Textarea)

outdooradventures/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils import timezone
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from .models import *
from django.views.decorators.csrf import csrf_protect
from .forms import CreatePostForm

def index(request):
    template = loader.get_template('outdooradventures/index.html')
    return HttpResponse(template.render({},request))


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        print(username, password)

        user = authenticate(request,username=username, password=password)
        if user is not None:
            auth_login(request, user)
            print('user exists')
            print(request.session.items())
        else:
            print('user does not exist')
            print(request.session.items())

    return render(request, 'outdooradventures/index.html')


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        name = request.POST.get('name')
        surname = request.POST.get('surname')

        print(username,email, password, name, surname)

        try:
            user=  User.objects.create_user(username, email=email, password=password, first_name=name, last_name=surname)
            user.save()
            auth_login(request, user)
            print(request.session.items())
        except Exception as e:
            print(e)

    return redirect('/')



def logout(request):
    auth_logout(request)
    template = loader.get_template('outdooradventures/index.html')
    return HttpResponse(template.render({},request))
    print(request.session.items())


def activities(request):
    print(request.session.items())
    template = loader.get_template('outdooradventures/activities.html')
    return HttpResponse(template.render({},request))



def createpost(request):

    template = loader.get_template('outdooradventures/createpost.html')
    return HttpResponse(template.render({},request))





"""for future use

    template = loader.get_template('outdooradventures/createpost.html')
    return HttpResponse(template.render({},request))

def userprofile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    return render(request, 'outdooradventures/...', {'user': user})

def clubprofile(request, club_id):
    club = get_object_or_404(Club, pk=club_id)
    return render(request, 'outdooradventures/...', {'club': club})

def activities(request):
    activities = Activity.objects.values('name')
    return render(request, 'outdooradventures/...', {'activities': activities})

def destinations(request):
    destinations = Adress.objects.values('city').distinct()
    return render(request, 'outdooradventures/...', {'destinations': destinations})

def userdashboard(request, user_id):
    return render(request, 'outdooradventures/...')

def clubdashboard(request, user_id):
    return render(request, 'outdooradventures/...')


"""

outdooradventures/templates/outdooradventures/activities.html
{% extends "outdooradventures/base.html" %}


{% block content %}


{% endblock %}

outdooradventures/templates/outdooradventures/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Outdoor Adventures</title>
    <!-- Bootstrap core CSS -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
     <!-- Custom fonts-->
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
     <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css" rel="stylesheet" type="text/css">
     <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
     <!-- Custom styles for this page -->
    <link href="../../static/css/landing-page.css" rel="stylesheet">
  </head>


  <link rel="shortcut icon" href="../../static/img/logomin.PNG" />
  <body>

      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
     	  <a href="#" class="navbar-left"><img src="../../static/img/logosmall.png" class="img-fluid" alt="Outdoor Logo"></a>
     	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     		<span class="navbar-toggler-icon"></span>
     	  </button>

     	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
     		<ul class="navbar-nav mr-auto">
     		  <li class="nav-item active">
     			<a class="nav-link" href="{% url 'outdooradventures:index'%}">Home <span class="sr-only">(current)</span></a>
     		  </li>
     		  <li class="nav-item">
     			<a class="nav-link" href="{% url 'outdooradventures:activities'%}">Activities</a>
     		  </li>
     		   <li class="nav-item">
     			<a class="nav-link" href="#">Destinations</a>
     		  </li>
          <li class="nav-item">
            <a class="nav-link" href="#">For Professionals...</a>
          </li>

     		</ul>

        {% if session.user is None %}
     		<button type="button" class="btn btn-primary col-md-1" data-toggle="modal" data-target="#loginModal">Sign in</button>
        {% elif session.user is not None%}
     		<li class="nav-item dropdown">
     			<a class="dropdown-toggle btn btn-default" id="navbarDropdown"  data-toggle="dropdown"  aria-expanded="true">
     			   Username
     			</a>
     			<div class="dropdown-menu">
     			  <a class="dropdown-item" href="#">Dashboard</a>
     			  <a class="dropdown-item" href="#">Profile</a>
     			  <div class="dropdown-divider"></div>
     			  <a class="dropdown-item" data-toggle="modal" data-target="#logoutModal">Logout</a>
     			</div>
     		</li>
        {% endif %}
     	  </div>
     	</nav>

{% block content %}

{% endblock %}


<!-- Footer -->
    <footer class="footer bg-dark">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
            <ul class="list-inline mb-2">
              <li class="list-inline-item">
                <a href="#">About</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Contact</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
            </ul>
            <p class="text-muted small mb-4 mb-lg-0">&copy; Outdoor Adventures 2018. All Rights Reserved.</p>
          </div>
          <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
            <ul class="list-inline mb-0">
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fab fa-facebook fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item mr-3">
                <a href="#">
                  <i class="fab fa-twitter-square fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fab fa-instagram fa-2x fa-fw"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>



      <!-- Login  Modal -->
      <div class="modal" id="loginModal">
      <div class="modal-dialog">
          <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Sign in</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <form  action="{% url 'outdooradventures:login'%}" method="post">
              {% csrf_token %}
              <div class="form-group">
                <label for="inputusername">Username</label>
                <input type="text" name="username" class="form-control" id="inputusermail"  placeholder="Enter username" required>
              </div>
              <div class="form-group">
                <label for="inputpassword">Password</label>
                <input type="password" name="password" class="form-control" id="inputpassword" placeholder="Password" required>
              </div>
              <div class="form-group">
                  <div class="offset-4">
                  <button type="submit" class="btn btn-primary">Sign in</button>
                  <button type="reset" class="btn btn-danger"> Cancel</button>
                  </div>
              </div>
              <div class="form-group">
                <div class="row">
                    <div class="col-lg-12">
                      <div class="text-center">
                      <p>Not a user? <a data-dismiss="modal" data-toggle="modal" data-target="#registerModal" tabindex="5" class="forgot-password">Sign Up</a></p>
                      </div>
                    </div>
                  </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>


    <!-- Register Modal -->
    <div class="modal" id="registerModal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Sign up</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
              <form action="{% url 'outdooradventures:register'%}" method="post">
                {% csrf_token %}
                {{ form }}
              <div class="form-group">
                <label for="inputusername">Username</label>
                <input type="text" name="username" class="form-control" id="inputtext"  placeholder="Enter username"  required>
              </div>
              <div class="form-group">
                <label for="inputemail">Email Adress</label>
                <input type="email" name="email" class="form-control" id="inputemail"  placeholder="Enter email"  required>
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              </div>
              <div class="form-group">
                <label for="inputname">Name</label>
                <input type="text" name="name" class="form-control" id="inputtext"  placeholder="Enter name"  required>
              </div>
              <div class="form-group">
                <label for="inputsurname">Surname</label>
                <input type="text" name="surname" class="form-control" id="inputtext"  placeholder="Enter surname" required>
              </div>
              <div class="form-group">
                <label for="inputpassword">Password</label>
                <input type="password" name="password" class="form-control" id="inputpassword" placeholder="Password" required>
              </div>
              <div class="form-group">
                <div class="offset-4">
                    <button type="Submit" class="btn btn-primary">Register</button>
                  <button type="reset" class="btn btn-danger"> Cancel</button>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                    <div class="col-lg-12">
                    <div class="text-center">
                      <p>Already a user? <a data-dismiss="modal" data-toggle="modal" data-target="#loginModal" tabindex="5" class="forgot-password">Sign in</a></p>
                      </div>
                    </div>
                  </div>
              </div>
              </form>
            </div>
        </div>
      </div>
    </div>




    <!-- Logout Modal -->
    <div class="modal" id="logoutModal">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h4 class="modal-title">Are you sure?</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
            <div class="modal-body">
            <form action="{% url 'outdooradventures:logout'%}" method="post">
              {% csrf_token %}
              <div class="form-group">
                <div class="offset-4">
                    <button type="Submit" class="btn btn-primary">Logout</button>
                  <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancel</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>


    <!-- Bootstrap core JavaScript -->
  	<script>
  		$(document).ready(function(){
  			$(".showcase-img:hover").hover(function(){
  				$(this).css("background", "#f5f5f5");
  			}, function(){
  				$(this).css("background", "#fff");
  			});
  		});

  	</script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

  </body>
</html>

outdooradventures/templates/outdooradventures/createpost.html
{% extends "outdooradventures/base.html" %}


{% block content %}

    <!-- Landing Page -->
    <header class="masthead text-white text-center">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5 title">Excited to find your next adventure?</h1>
			<h3>Create a post and offers will get to you!!!</h3> <br>
			<div id="postform" class="offset-3">
				<form action="{% url 'outdooradventures:createpost'%}" method="post">
              {% csrf_token %}
							<div class="form-group">
								<input type="text" class="form-control col-md-8" id="inputactivity"  placeholder="Activity*">
							</div>
							<div class="form-group">
								<input type="text" class="form-control col-md-8" id="inputdestination"  placeholder="Destination*">
							</div>
							<div class="form-group">
								<input type="text" class="form-control col-md-8" id="inputnoparticipants"  placeholder="Num. of Participants*">
							</div>
							<div class="form-group">
								<input type="date" class="form-control col-md-8" id="inputdate"  placeholder="Date*">
							</div>
							<div class="form-group">
								<textarea type="text" class="form-control col-md-8" id="inputcomments"  placeholder="Comments"></textarea>
							</div>
							<div class="form-group">
								<button type="submit" class="btn btn-block btn-lg btn-warning col-md-2 offset-3">Publish</button>
							</div>
				</form>
			</div>

          </div>
        </div>
      </div>
    </header>



{% endblock %}

outdooradventures/templates/outdooradventures/index.html
{% extends "outdooradventures/base.html" %}


{% block content %}

    <!-- Landing Page -->
    <header class="masthead text-white text-center">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5">Excited to find your next adventure?</h1>
		      	<p>Experience nature to the fullest!</p>
		      	<p>Connect with clubs or indep. professionals that organize outdoor activities.</p>
		      	<p class="hashtags">#risktakers #adventures<p/>
		      	<div class="col-md-6 col-lg-4 col-xl-3 mx-auto">
			    	      <button  class="btn btn-block btn-lg btn-warning" >
                    <a href="{% url 'outdooradventures:createpost'%}">Get Started!</a>
                  </button>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Icons Grid -->
    <section class="features-icons bg-light text-center">
      <div class="container">
  	    <div class="row">
    			<div class="col-lg-12">
    			   <img src="../../static/img/purpose.PNG" class="img-fluid" alt="Responsive image">
          </div>
  		  </div>
        <div class="row">
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="fas fa-hiking m-auto text-primary"></i>
              </div>
              <h4>Pick an adventure</h4>
              <p class="lead mb-0">What would you like to experience, what outdoor activity do you want to do?</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="fas fa-globe-africa m-auto text-primary"></i>
              </div>
              <h4>Pick a place</h4>
              <p class="lead mb-0">In which place do you prefer experiencing you next outdoor adventure?</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="features-icons-item mx-auto mb-0 mb-lg-3">
              <div class="features-icons-icon d-flex">
                <i class="icon-check m-auto text-primary"></i>
              </div>
              <h4>Publish your post</h4>
              <p class="lead mb-0">Fill in the form, post it and offers will reach you!</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Image Showcases -->
    <section class="showcase">
      <div class="container-fluid p-0">
        <div class="row no-gutters">
    		  <div class="col-lg-4 col-md-4 text-white showcase-img" style="background-image: url('../../static/img/sailing.png');"></div>
    		  <div class="col-lg-4 col-md-4 text-white showcase-img" style="background-image: url('../../static/img/sup.jpg');"></div>
    		  <div class="col-lg-4 col-md-4 text-white showcase-img" style="background-image: url('../../static/img/windsurfing.jpg');"></div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-4 col-md-4 text-white showcase-img" style="background-image: url('../../static/img/mountain.jpg');"></div>
    		  <div class="col-lg-4 col-md-4 text-white showcase-img" style="background-image: url('../../static/img/bungee.jpg');"></div>
    		  <div class="col-lg-4 col-md-4 text-white showcase-img" style="background-image: url('../../static/img/flying.jpg');"></div>
        </div>
		    <div class="row no-gutters">
          <div class="col-lg-4 col-md-4 text-white showcase-img" style="background-image: url('../../static/img/skiing.jpg');"></div>
    		  <div class="col-lg-4 col-md-4 text-white showcase-img" style="background-image: url('../../static/img/climbing.jpg');"></div>
    		  <div class="col-lg-4 col-md-4 text-white showcase-img" style="background-image: url('../../static/img/hiking.jpg');"></div>
        </div>
      </div>
    </section>

	<!-- message and user guidelines -->
    <section class="features-icons bg-light text-center">
      <div class="container">
    		<div class="row">
    			<div class="col-lg-12">
    			   <img src="../../static/img/message.PNG" class="img-fluid" alt="Responsive image">
          </div>
    		</div>
    		<div class="row">
    			<div class="col-lg-12">
    			   <img src="../../static/img/example.png" class="img-fluid" alt="Responsive image">
    			</div>
    		</div>
      </div>
    </section>


{% endblock %}